### ISSUE TITLE
Problem with compiling react js file on windows

### ISSUE THREAD

**Issue by cthippan** [airavata-courses/TeamOmega#1]
![isuue-1](https://cloud.githubusercontent.com/assets/16846165/18328810/666924ae-7505-11e6-97c8-b1a53f614c95.png)

**Comment by sagarkrkv** [comment]
In the environment variables, check if your TEMP variable has more than 1 entry, copy paste the entries here.

**Comment by cthippan** [comment]
it has only one entry - %USERPROFILE%\AppData\Local\Temp

**Comment by sagarkrkv** [comment]
Install the babel module for compiling react files.

> npm install babel-plugin-transform-react-jsx

**Comment by songires** [comment]
Chaitra, can you install Zoom, we can share screen and sort something out for this issue
