### ISSUE TITLE
Let us meet for a project discussion today

### ISSUE THREAD

**Issue by njetty** [airavata-courses/TeamOmega#10]
Location: Info West
Time: 2:30 PM - 3:30 PM

**Comment by cthippan** [comment]
I have a class from 2:30 pm to 3:45 pm today.

**Comment by sagarkrkv** [comment]
I have a class from 1-4

**Comment by songires** [comment]
how about in the evening?
After 7 may b

**Comment by njetty** [comment]
Meeting postponed to 7:00 PM
