### ISSUE TITLE
Branching

### ISSUE THREAD

**Issue by songires** [airavata-courses/TeamOmega#2]
Guys, I believe we should create one more branch from master as 'develop' from where all of us can can create our own individual branches. So as Chaitra directly created her own feature branch, I think she should create her separate feature branch from 'develop' branch and not 'master' branch. Correct me if I am wrong.

**Comment by sagarkrkv** [comment]
We can merge any branch with any branch, so we can merge all the feature branches to a new develop branch. Once a feature branch is stable we will merge it with develop.
