### ISSUE TITLE
Auth0 in frontend or backend ?

### ISSUE THREAD

**Issue by sagarkrkv** [airavata-courses/TeamOmega#3]
Where do you guys think we should implement the authentication module, frontend or backend ?

**Comment by songires** [comment]
Authentication will be done at the backend, I think we cannot do it on front end, credentials should be supplied to backend, of they match, access is granted else same page is requested again by the server with a message if invalid credentials.

Front end will only be used for content verification, for example username should be email id, or fields are not empty

**Comment by sagarkrkv** [comment]
We are using an external API for authentication called Auth0, the authentication is not handled on our side.

If we go for front-end authentication, the front will receive an authentication token from the Auth0 api, its called a jwt token(its based on json format). the jwt is passed on to the backend.

If we go for backend authentication, the backend will communicate with Auth0 api for authentication, and it'll receive the jwt token.

Overall I think implementing the authentication process in front end will make the system more scalable.

[https://auth0.com/docs/quickstart/spa/react/01-login](https://auth0.com/docs/quickstart/spa/react/01-login)

**Comment by sagarkrkv** [comment]
@cthippan  go through this when you get a chance [https://auth0.com/docs/quickstart/spa/react/01-login](https://auth0.com/docs/quickstart/spa/react/01-login)

@songires  go through this when you get a chance [https://auth0.com/docs/quickstart/webapp/nodejs](https://auth0.com/docs/quickstart/webapp/nodejs)

**Comment by sagarkrkv** [comment]
Completed.
