### ISSUE TITLE
Crashing of micro service after submitting the job

### ISSUE THREAD

**Issue by cthippan** [airavata-courses/TeamOmega#34]

**Comment by cthippan** [comment]
I think we should be able to kill that task gracefully.

**Comment by sagarkrkv** [comment]
Which service crashed ? have you implemented the thrift api ?

**Comment by cthippan** [comment]
we can set short timeouts so that the framework don't hold the offer(api call) for a long time.Even in case of master fail over, mesos doesn't resend offers so we can reconnect with the same framework id and resume the tasks by re-registering.
In case of failure of slave servers we can assign checkpoints and kill all the tasks if that server goes down.
