### ISSUE TITLE
In-memory database to store station codes

### ISSUE THREAD

**Issue by sagarkrkv** [airavata-courses/TeamOmega#6]
Hey guys, I'm thinking of using a very lightweight in-memory database, preferably a JavaScript based one for storing and querying station names and codes, and their respective date ranges. The advantage of it being javascript based, is we can move it to front-end if required. 

I have found one DB for this task, [NeDB](https://github.com/louischatriot/nedb) its compatible with NodeJS and its pretty fast. We only have about 150 station names.

> Insert: 10,680 ops/s
> Find: 43,290 ops/s
> Update: 8,000 ops/s
> Remove: 11,750 ops/s

Let me know what you think

**Comment by njetty** [comment]
Done..
