### ISSUE TITLE
Integrating Auth0 with React

### ISSUE THREAD

**Issue by sagarkrkv** [airavata-courses/TeamOmega#8]
@cthippan We discussed on how to implement Auth0 service in ReactJS and pass on the tokens to backend. I have found this [resource](https://davidwalsh.name/react-authentication) which I believe will be helpful for us. Once go through it.

**Comment by cthippan** [comment]
sure!

**Comment by sagarkrkv** [comment]
Implemented auth0 authentication on server side, if possible we'll try to move it to client side.
